name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cross
      run: cargo install cross
    - name: Start cross
      run: sudo systemctl start docker
    - name: Add build targets for Windows
      run: rustup target add x86_64-pc-windows-gnu #; rustup target add i686-pc-windows-msvc
    - name: Build for Windows
      run: cross build --release --target=x86_64-pc-windows-gnu #; cross build --release --target=i686-pc-windows-msvc
    - name: Add build target for Linux
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Build for Linux
      run: cargo build --release #--target=x86_64-unknown-linux-gnu
    - name: Add build target for MacOS
      run: rustup target add x86_64-apple-darwin
#     - name: Build for MacOS
#       run: cross build --release --target=x86_64-apple-darwin
    - name: Run tests
      run: cargo test --verbose
    - name: Create build directories
      run: mkdir -p builds/licensesnip-win64; mkdir -p builds/licensesnip-linux; mkdir -p builds/licensesnip-macos
    - name: Copy builds into build directories
      run: dir target; cp target/x86_64-pc-windows-gnu/release/licensesnip.exe builds/licensesnip-win64; cp target/release/licensesnip.exe builds/licensesnip-linux #; cp target/x86_64-apple-darwin/release/licensesnip.exe builds/licensesnip-macos #; cp target/i686-pc-windows-msvc/release/licensesnip.exe builds/licensesnip-win32   
    - name: Zip builds into tar.gz
      run: tar -C builds -czvf licensesnip-win64.tar.gz licensesnip-win64; tar -C builds -czvf licensesnip-linux.tar.gz licensesnip-linux #; tar -C builds -czvf licensesnip-macos.tar.gz licensesnip-macos #; tar -C builds -czvf licensesnip-win32.tar.gz licensesnip-win32 
    - name: Check dir
      run: dir; dir builds; dir builds/x86_64-pc-windows-gnu
    - name: Upload Windows build
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: licensesnip-win64.tar.gz # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: builds/x86_64-pc-windows-gnu/x86_64-pc-windows-gnu.tar.gz
        # The desired behavior if no files are found using the provided path.
